kind: pipeline
name: default

steps:
  - name: setup
    image: registry:5000/node-build
    commands:
      - yarn
    when:
    branch:
    - master

  - name: test
    image: registry:5000/node-build
    commands:
      - yarn lint
      - yarn test
    when:
    branch:
    - master

  - name: build
    image: registry:5000/node-build
    commands:
      - yarn compile
    when:
    branch:
    - master

  - name: publish
    image: registry:5000/node-build
    commands:
      - yarn publish --access public
    when:
    branch:
    - master
